import "./index.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Cristian Rodriguez | technical test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Component to handle small alerts with sonner */}
      <Toaster expand={true} offset="37px" position="bottom-right" richColors />

      <body>{children}</body>
    </html>
  );
}
